export const BookingActionTypes = {
  SET_SPECIALIST: "SET_SPECIALIST",
  ADD_CART_ITEM: "ADD_ITEM",
  REMOVE_CART_ITEM: "REMOVE_CART_ITEM",
  CLEAR_CART: "CLEAR_CART",
  SELECT_FACILITY: "SELECT_FACILITY",
  SET_MEETING_TIME: "SET_MEETING_TIME",
  SET_STEP: "SET_STEP",
  SELECT_SPECIALIST:"SELECT_SPECIALIST",

  SET_CURRENT_SERVICE: "SET_CURRENT_SERVICE",
  SET_CURRENT_CATEGORY: "SET_CURRENT_CATEGORY",
  SET_PRICE_RANGE: "SET_PRICE_RANGE",
  SET_TARGET_GENDER: "SET_TARGET_GENDER",
  SET_PRO_GENDER: "SET_PRO_GENDER",
  SET_SORT_METHOD: "SET_SORT_METHOD",
  SET_SORT_FACILITY_METHOD: "SET_SORT_FACILITY_METHOD",
  SET_SHOW_RESULTS: "SET_SHOW_RESULTS",
  SET_SEARCH_RADIUS: "SET_SEARCH_RADIUS",
  SET_SEARCH_LOCATION: "SET_SEARCH_LOCATION"
};
