export const FacilityCreationActionTypes = {
  SET_FACILITY_LOCATION: "SET_FACILITY_LOCATION",
  SET_FACILITY_NAME: "SET_FACILITY_NAME",
  SET_FACILITY_DESCRIPTION: 'SET_FACILITY_DESCRIPTION',
  SET_FACILITY_WORKING_HOURS: "SET_FACILITY_WORKING_HOURS",
  SET_FACILITY_SEAT_CAPACITY: "SET_FACILITY_SEAT_CAPACITY",
  SET_FACILITY_GALLERY: "SET_FACILITY_GALLERY"
}
